import { StrictMode } from 'react';
import * as ReactDOM from 'react-dom/client';
import './index.css';
import { QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { ThemeProvider } from '@/components/theme-provider';
// Initializes i18next synchronously — resources are statically bundled, so no
// <Suspense> boundary is needed. Adding an HTTP backend or lazy locale imports
// later would change that.
import '@/i18n';
import { queryClient } from './lib/query-client';
import { setNavigateCallback } from './services/api-client';
// Generated by @tanstack/router-plugin from src/routes.
import { routeTree } from './routeTree.gen';

const router = createRouter({ routeTree });

// Lets the axios interceptor redirect without importing the router, keeping the
// service layer free of routing dependencies.
setNavigateCallback((path) => router.navigate({ to: path }));

// Register the router instance for type safety.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement,
);

root.render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
        <RouterProvider router={router} />
      </ThemeProvider>
    </QueryClientProvider>
  </StrictMode>,
);
