/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as BranchesNewRouteImport } from './routes/branches/new'
import { Route as CheckInsIndexRouteImport } from './routes/check-ins/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersNewRouteImport } from './routes/members/new'
import { Route as MembershipPlansIndexRouteImport } from './routes/membership-plans/index'
import { Route as MembershipPlansNewRouteImport } from './routes/membership-plans/new'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffNewRouteImport } from './routes/staff/new'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as BranchesBranchIdEditRouteImport } from './routes/branches/$branchId.edit'
import { Route as MembersMemberIdIndexRouteImport } from './routes/members/$memberId.index'
import { Route as MembersMemberIdEditRouteImport } from './routes/members/$memberId.edit'
import { Route as MembersMemberIdSellRouteImport } from './routes/members/$memberId.sell'
import { Route as MembershipPlansPlanIdEditRouteImport } from './routes/membership-plans/$planId.edit'
import { Route as RolesRoleIdPermissionsRouteImport } from './routes/roles/$roleId.permissions'
import { Route as StaffStaffIdIndexRouteImport } from './routes/staff/$staffId.index'
import { Route as StaffStaffIdEditRouteImport } from './routes/staff/$staffId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesNewRoute = BranchesNewRouteImport.update({
  id: '/branches/new',
  path: '/branches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInsIndexRoute = CheckInsIndexRouteImport.update({
  id: '/check-ins/',
  path: '/check-ins/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipPlansIndexRoute = MembershipPlansIndexRouteImport.update({
  id: '/membership-plans/',
  path: '/membership-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipPlansNewRoute = MembershipPlansNewRouteImport.update({
  id: '/membership-plans/new',
  path: '/membership-plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchIdEditRoute = BranchesBranchIdEditRouteImport.update({
  id: '/branches/$branchId/edit',
  path: '/branches/$branchId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdIndexRoute = MembersMemberIdIndexRouteImport.update({
  id: '/members/$memberId/',
  path: '/members/$memberId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdEditRoute = MembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdSellRoute = MembersMemberIdSellRouteImport.update({
  id: '/members/$memberId/sell',
  path: '/members/$memberId/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipPlansPlanIdEditRoute =
  MembershipPlansPlanIdEditRouteImport.update({
    id: '/membership-plans/$planId/edit',
    path: '/membership-plans/$planId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const RolesRoleIdPermissionsRoute = RolesRoleIdPermissionsRouteImport.update({
  id: '/roles/$roleId/permissions',
  path: '/roles/$roleId/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdIndexRoute = StaffStaffIdIndexRouteImport.update({
  id: '/staff/$staffId/',
  path: '/staff/$staffId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdEditRoute = StaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/branches/new': typeof BranchesNewRoute
  '/members/new': typeof MembersNewRoute
  '/membership-plans/new': typeof MembershipPlansNewRoute
  '/staff/new': typeof StaffNewRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/check-ins/': typeof CheckInsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/membership-plans/': typeof MembershipPlansIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/branches/$branchId/edit': typeof BranchesBranchIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/sell': typeof MembersMemberIdSellRoute
  '/membership-plans/$planId/edit': typeof MembershipPlansPlanIdEditRoute
  '/roles/$roleId/permissions': typeof RolesRoleIdPermissionsRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
  '/staff/$staffId/': typeof StaffStaffIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/branches/new': typeof BranchesNewRoute
  '/members/new': typeof MembersNewRoute
  '/membership-plans/new': typeof MembershipPlansNewRoute
  '/staff/new': typeof StaffNewRoute
  '/attendance': typeof AttendanceIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/check-ins': typeof CheckInsIndexRoute
  '/members': typeof MembersIndexRoute
  '/membership-plans': typeof MembershipPlansIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/users': typeof UsersIndexRoute
  '/branches/$branchId/edit': typeof BranchesBranchIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/sell': typeof MembersMemberIdSellRoute
  '/membership-plans/$planId/edit': typeof MembershipPlansPlanIdEditRoute
  '/roles/$roleId/permissions': typeof RolesRoleIdPermissionsRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/members/$memberId': typeof MembersMemberIdIndexRoute
  '/staff/$staffId': typeof StaffStaffIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/branches/new': typeof BranchesNewRoute
  '/members/new': typeof MembersNewRoute
  '/membership-plans/new': typeof MembershipPlansNewRoute
  '/staff/new': typeof StaffNewRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/check-ins/': typeof CheckInsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/membership-plans/': typeof MembershipPlansIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/branches/$branchId/edit': typeof BranchesBranchIdEditRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/members/$memberId/sell': typeof MembersMemberIdSellRoute
  '/membership-plans/$planId/edit': typeof MembershipPlansPlanIdEditRoute
  '/roles/$roleId/permissions': typeof RolesRoleIdPermissionsRoute
  '/staff/$staffId/edit': typeof StaffStaffIdEditRoute
  '/members/$memberId/': typeof MembersMemberIdIndexRoute
  '/staff/$staffId/': typeof StaffStaffIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/branches/new'
    | '/members/new'
    | '/membership-plans/new'
    | '/staff/new'
    | '/attendance/'
    | '/branches/'
    | '/check-ins/'
    | '/members/'
    | '/membership-plans/'
    | '/payments/'
    | '/roles/'
    | '/staff/'
    | '/users/'
    | '/branches/$branchId/edit'
    | '/members/$memberId/edit'
    | '/members/$memberId/sell'
    | '/membership-plans/$planId/edit'
    | '/roles/$roleId/permissions'
    | '/staff/$staffId/edit'
    | '/members/$memberId/'
    | '/staff/$staffId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/branches/new'
    | '/members/new'
    | '/membership-plans/new'
    | '/staff/new'
    | '/attendance'
    | '/branches'
    | '/check-ins'
    | '/members'
    | '/membership-plans'
    | '/payments'
    | '/roles'
    | '/staff'
    | '/users'
    | '/branches/$branchId/edit'
    | '/members/$memberId/edit'
    | '/members/$memberId/sell'
    | '/membership-plans/$planId/edit'
    | '/roles/$roleId/permissions'
    | '/staff/$staffId/edit'
    | '/members/$memberId'
    | '/staff/$staffId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/branches/new'
    | '/members/new'
    | '/membership-plans/new'
    | '/staff/new'
    | '/attendance/'
    | '/branches/'
    | '/check-ins/'
    | '/members/'
    | '/membership-plans/'
    | '/payments/'
    | '/roles/'
    | '/staff/'
    | '/users/'
    | '/branches/$branchId/edit'
    | '/members/$memberId/edit'
    | '/members/$memberId/sell'
    | '/membership-plans/$planId/edit'
    | '/roles/$roleId/permissions'
    | '/staff/$staffId/edit'
    | '/members/$memberId/'
    | '/staff/$staffId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BranchesNewRoute: typeof BranchesNewRoute
  MembersNewRoute: typeof MembersNewRoute
  MembershipPlansNewRoute: typeof MembershipPlansNewRoute
  StaffNewRoute: typeof StaffNewRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  CheckInsIndexRoute: typeof CheckInsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MembershipPlansIndexRoute: typeof MembershipPlansIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  BranchesBranchIdEditRoute: typeof BranchesBranchIdEditRoute
  MembersMemberIdEditRoute: typeof MembersMemberIdEditRoute
  MembersMemberIdSellRoute: typeof MembersMemberIdSellRoute
  MembershipPlansPlanIdEditRoute: typeof MembershipPlansPlanIdEditRoute
  RolesRoleIdPermissionsRoute: typeof RolesRoleIdPermissionsRoute
  StaffStaffIdEditRoute: typeof StaffStaffIdEditRoute
  MembersMemberIdIndexRoute: typeof MembersMemberIdIndexRoute
  StaffStaffIdIndexRoute: typeof StaffStaffIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/new': {
      id: '/branches/new'
      path: '/branches/new'
      fullPath: '/branches/new'
      preLoaderRoute: typeof BranchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-ins/': {
      id: '/check-ins/'
      path: '/check-ins'
      fullPath: '/check-ins/'
      preLoaderRoute: typeof CheckInsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-plans/': {
      id: '/membership-plans/'
      path: '/membership-plans'
      fullPath: '/membership-plans/'
      preLoaderRoute: typeof MembershipPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-plans/new': {
      id: '/membership-plans/new'
      path: '/membership-plans/new'
      fullPath: '/membership-plans/new'
      preLoaderRoute: typeof MembershipPlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchId/edit': {
      id: '/branches/$branchId/edit'
      path: '/branches/$branchId/edit'
      fullPath: '/branches/$branchId/edit'
      preLoaderRoute: typeof BranchesBranchIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/': {
      id: '/members/$memberId/'
      path: '/members/$memberId'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof MembersMemberIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/edit': {
      id: '/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof MembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/sell': {
      id: '/members/$memberId/sell'
      path: '/members/$memberId/sell'
      fullPath: '/members/$memberId/sell'
      preLoaderRoute: typeof MembersMemberIdSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-plans/$planId/edit': {
      id: '/membership-plans/$planId/edit'
      path: '/membership-plans/$planId/edit'
      fullPath: '/membership-plans/$planId/edit'
      preLoaderRoute: typeof MembershipPlansPlanIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$roleId/permissions': {
      id: '/roles/$roleId/permissions'
      path: '/roles/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof RolesRoleIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/': {
      id: '/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId/'
      preLoaderRoute: typeof StaffStaffIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId/edit': {
      id: '/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/staff/$staffId/edit'
      preLoaderRoute: typeof StaffStaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  BranchesNewRoute: BranchesNewRoute,
  MembersNewRoute: MembersNewRoute,
  MembershipPlansNewRoute: MembershipPlansNewRoute,
  StaffNewRoute: StaffNewRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  CheckInsIndexRoute: CheckInsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  MembershipPlansIndexRoute: MembershipPlansIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  BranchesBranchIdEditRoute: BranchesBranchIdEditRoute,
  MembersMemberIdEditRoute: MembersMemberIdEditRoute,
  MembersMemberIdSellRoute: MembersMemberIdSellRoute,
  MembershipPlansPlanIdEditRoute: MembershipPlansPlanIdEditRoute,
  RolesRoleIdPermissionsRoute: RolesRoleIdPermissionsRoute,
  StaffStaffIdEditRoute: StaffStaffIdEditRoute,
  MembersMemberIdIndexRoute: MembersMemberIdIndexRoute,
  StaffStaffIdIndexRoute: StaffStaffIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
